apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: helloworld
build:
  artifacts:
    - image: smana/helloworld
      sync:
        infer: ["**/*.html"]
deploy:
  helm:
    flags:
      install:
        - "--create-namespace"
    releases:
      - name: helloworld
        chartPath: charts/helloworld
        namespace: demo
        artifactOverrides:
          image: "smana/helloworld"
profiles:
  - name: "local"
    deploy:
      helm:
        flags:
          install:
            - "--create-namespace"
        releases:
          - name: helloworld
            chartPath: charts/helloworld
            namespace: demo
            artifactOverrides:
              image: "smana/helloworld"
    test:
      - image: smana/helloworld
        structureTests:
          - "./tests/structure/*"
    build:
      artifacts:
        - image: smana/helloworld
          docker:
            target: "tester"
          sync:
            infer: ["**/*.html"]
